on:
  push:
  workflow_dispatch:

jobs:
  build_app:
    name: Build App
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4
    - name: Install act
      env:
        GH_TOKEN: ${{ github.token }}
      run: gh extension install https://github.com/nektos/gh-act
    - name: Checkout Target repo
      uses: actions/checkout@v4
      with:
        repository: 2dust/v2rayNG
        path: ./target
        submodules: 'recursive'
        fetch-depth: '0'
    - name: Run Workflow with act
      env:
        GH_TOKEN: ${{ github.token }}
      run: |
        cd ./target
        # Select `Medium` -> Use -P option
        # -P ubuntu-latest=-self-hosted -> Run without docker
        gh extension exec act \
          -W '.github/workflows/build.yml' \
          -P ubuntu-latest=-self-hosted \
          -s GITHUB_TOKEN="${{ github.token }}" \
          -s APP_KEYSTORE_BASE64="${{ secrets.APP_KEYSTORE_BASE64 }}" \
          -s APP_KEYSTORE_PASSWORD="${{ secrets.APP_KEYSTORE_KEY_PASSWORD }}" \
          -s APP_KEYSTORE_ALIAS="${{ secrets.APP_KEYSTORE_ALIAS }}" \
          -s APP_KEY_PASSWORD="${{ secrets.APP_KEYSTORE_KEY_PASSWORD }}" \
          --artifact-server-path $PWD/.artifacts
    - name: List Artifacts
      run: tree -a ./target/.artifacts

  upload_artifacts:
    runs-on: ubuntu-latest
    needs: build_app
    strategy:
      matrix:
        abi: [arm64-v8a, armeabi-v7a, x86]
    steps:
    - name: Upload Artifacts
      uses: actions/upload-artifact@v4
      with:
        name: ${{ matrix.abi }}
        path: ./target/.artifacts/**/*${{ matrix.abi }}*.zip
