on:
  push:
  workflow_dispatch:

jobs:
  build_app:
    name: Build App
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4
    - name: Install act
      env:
        GH_TOKEN: ${{ github.token }}
      run: gh extension install https://github.com/nektos/gh-act
    - name: Checkout Target repo
      uses: actions/checkout@v4
      with:
        repository: 2dust/v2rayNG
        path: ./target
        submodules: 'recursive'
        fetch-depth: '0'
    - name: Run Workflow with act
      env:
        GH_TOKEN: ${{ github.token }}
      run: |
        cd ./target
        # Select `Medium` -> Use -P option
        gh extension exec act -W '.github/workflows/build.yml' -P ubuntu-latest=catthehacker/ubuntu:act-latest
