on:
  push:
  workflow_dispatch:

jobs:
  build_app:
    name: Build App
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4
    - name: Install act
      run: gh extension install https://github.com/nektos/gh-act
      env:
        GH_TOKEN: ${{ github.token }}
    - name: Checkout Target repo
      uses: actions/checkout@v4
      with:
        repository: 2dust/v2rayNG
        path: ./target
        submodules: true
    - name: Run Workflow with act
      run: |
        cd ./target
        act -W '.github/workflows/build.yml'
