on:
  workflow_dispatch:

jobs:
  build_app:
    name: Build App
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4
    - name: Install act
      run: gh extension install https://github.com/nektos/gh-act
